#!/bin/bash
cmsRun hltgsftrkanalyser_cfg.py testNcSuffix=NC2 outFile=nc6VsNc2_pt10_sharedHits3_passHltDEle33_narrow.root
cmsRun hltgsftrkanalyser_cfg.py testNcSuffix=NC3 outFile=nc6VsNc3_pt10_sharedHits3_passHltDEle33_narrow.root
cmsRun hltgsftrkanalyser_cfg.py testNcSuffix=NC4 outFile=nc6VsNc4_pt10_sharedHits3_passHltDEle33_narrow.root
cmsRun hltgsftrkanalyser_cfg.py testNcSuffix=NC5 outFile=nc6VsNc5_pt10_sharedHits3_passHltDEle33_narrow.root

cmsRun hltgsftrkanalyser_lowEt_cfg.py testNcSuffix=NC2 outFile=nc6VsNc2_pt10_sharedHits3_passHltEle25_narrow.root
cmsRun hltgsftrkanalyser_lowEt_cfg.py testNcSuffix=NC3 outFile=nc6VsNc3_pt10_sharedHits3_passHltEle25_narrow.root
cmsRun hltgsftrkanalyser_lowEt_cfg.py testNcSuffix=NC4 outFile=nc6VsNc4_pt10_sharedHits3_passHltEle25_narrow.root
cmsRun hltgsftrkanalyser_lowEt_cfg.py testNcSuffix=NC5 outFile=nc6VsNc5_pt10_sharedHits3_passHltEle25_narrow.root
cmsRun hltgsftrkanalyser_lowEt_kfTrk_cfg.py outFile=nc6VsKf_pt10_sharedHits3_passHltEle25_narrow.root

# vs. RECO
cmsRun hltgsftrkanalyser_vsReco_cfg.py testNcSuffix=NC2 outFile=recoVsNc2_pt10_dr0p5_passHltDEle33_narrow.root
cmsRun hltgsftrkanalyser_vsReco_cfg.py testNcSuffix=NC3 outFile=recoVsNc3_pt10_dr0p5_passHltDEle33_narrow.root
cmsRun hltgsftrkanalyser_vsReco_cfg.py testNcSuffix=NC4 outFile=recoVsNc4_pt10_dr0p5_passHltDEle33_narrow.root
cmsRun hltgsftrkanalyser_vsReco_cfg.py testNcSuffix=NC5 outFile=recoVsNc5_pt10_dr0p5_passHltDEle33_narrow.root
cmsRun hltgsftrkanalyser_vsReco_cfg.py outFile=recoVsNc6_pt10_dr0p5_passHltDEle33_narrow.root
# vs. RECO lowEt menu
cmsRun hltgsftrkanalyser_vsReco_lowEt_cfg.py testNcSuffix=NC2 outFile=recoVsNc2_pt10_dr0p5_passHltEle25_narrow.root
cmsRun hltgsftrkanalyser_vsReco_lowEt_cfg.py testNcSuffix=NC3 outFile=recoVsNc3_pt10_dr0p5_passHltEle25_narrow.root
cmsRun hltgsftrkanalyser_vsReco_lowEt_cfg.py testNcSuffix=NC4 outFile=recoVsNc4_pt10_dr0p5_passHltEle25_narrow.root
cmsRun hltgsftrkanalyser_vsReco_lowEt_cfg.py testNcSuffix=NC5 outFile=recoVsNc5_pt10_dr0p5_passHltEle25_narrow.root
cmsRun hltgsftrkanalyser_vsReco_lowEt_cfg.py outFile=recoVsNc6_pt10_dr0p5_passHltEle25_narrow.root
cmsRun hltgsftrkanalyser_vsReco_lowEt_kfTrk_cfg.py outFile=recoVsKf_pt10_dr0p5_passHltEle25_narrow.root

